spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_mybatis?serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    # 内置数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   # 配置全局懒加载
   lazy-loading-enabled: true
   aggressive-lazy-loading: false
